### ISSUE TITLE
Comments login error not use css

### ISSUE THREAD

**Issue by yerbol89** [amiyasahu/Donut#103]
Hi @amiyasahu 
Today i see Donut theme not use .donut-error, .qa-error for comments error. I search this function for add comments. But i could not find. Please add this css.

![2019-01-12_08-37-38](https://user-images.githubusercontent.com/993795/51068236-86b3de00-1645-11e9-96ce-9733bf23e1f1.png)

**Comment by amiyasahu** [comment]
I will take a look at this one in next version.
