### ISSUE TITLE
when there is no details for the questions, it looks odd on mobile

### ISSUE THREAD

**Issue by Marcin-Kozyra** [amiyasahu/Donut#104]
![SmartSelect_20190328-204304_Samsung_Internet](https://user-images.githubusercontent.com/1209361/55203833-db71ea00-519a-11e9-8eab-3ef9c8bcf319.jpg)

**Comment by amiyasahu** [comment]
I don't think I can do anything about this. How about setting the questions body as mandatory through -> Admin -> Posting -> "Minimum length of question body: "
