### ISSUE TITLE
How to fix thix issue 

### ISSUE THREAD

**Issue by dorandxhelili** [amiyasahu/Donut#107]
The question title in mobile theme not showing correctly, you can see in photo

![Screenshot_2019-07-03-21-54-42-192_com android chrome](https://user-images.githubusercontent.com/11158106/60684224-aca39800-9e9c-11e9-9fd4-f8ac7d333f1e.png)

**Comment by amiyasahu** [comment]
Are there this big English words in your forum?

**Comment by dorandxhelili** [comment]
The font is okey when i open in web, but when i open web in mobile, title not showin correctly.

**Comment by amiyasahu** [comment]
To fix this issue you can add below line into 
donut.css and donut-min.css file

```css
.qa-q-item-title a {
    word-wrap: break-word;
}
```

this will break the work to the new line. 

I am not adding this to the core theme as users wont expect to break the work into a new line. And as far as I know there are no words that is this long that wont fit mobile screen.
