### ISSUE TITLE
how to hide those sub_navigation

### ISSUE THREAD

**Issue by d0r1x** [amiyasahu/Donut#108]
how can i hide those sub category in question page

![Screenshot_2](https://user-images.githubusercontent.com/11158106/61080593-b477b500-a425-11e9-97c0-e3dfda36d42e.jpg)

**Comment by d0r1x** [comment]
hello Amiyasahu, can you provide me any answer for what i ask ?

**Comment by amiyasahu** [comment]
You can use css to do that.
```css
.subnav-row {
    display: none;
}
```
