### ISSUE TITLE
Old URL directs to scam 

### ISSUE THREAD

**Issue by ShalokShalom** [amiyasahu/Donut#123]
See this; http://amiyasahu.com/

Godot and many other communities still use this URL on the bottom of their page, so you might wanna inform your customers and users in some way

Good day

**Comment by amiyasahu** [comment]
Thanks for letting me know. I no longer own this domain since a very long time. 
It is hard to let everyone know about this URL, I can post this in q2a forum though.

**Comment by ShalokShalom** [comment]
Close, when its convenient for you.
