### ISSUE TITLE
There is some problem with "warn on leave" plugin.

### ISSUE THREAD

**Issue by gurjyot** [amiyasahu/Donut#15]
I was asking a question but when the time came to hit the "Ask the question", I got a message from warn on leave plugin that whether I want to stay on the page or leave it. 
Please have a look at the issue... as I have tested a lot of themes but those all work fine with that plugin.

**Comment by amiyasahu** [comment]
are you getting any error messages . Can you please check and let me know the error in JS Console

**Comment by amiyasahu** [comment]
I tested it  It works fine .
