### ISSUE TITLE
Error with wordpress integration 

### ISSUE THREAD

**Issue by amiyasahu** [amiyasahu/Donut#17]
The problem down to request being made to the qa-users table, which doesn't exist because I am integrating with Wordpress

A Question2Answer database query failed when generating this page.
A full description of the failure is available in the web server's error log file.

**Comment by codedr1** [comment]
Does this mean the theme does not support single sign-on (on q2a 1.6 or 1.7)?

**Comment by amiyasahu** [comment]
yes . As of v1.0 this does not support wordpress integration .it will be fixed in next release .

**Comment by toby78** [comment]
Same issue here, however not wordpress but own sso solution

**Comment by amiyasahu** [comment]
fixed in dev branch
