### ISSUE TITLE
on-site-notifications plugin not showing with the Donut theme

### ISSUE THREAD

**Issue by ghost** [amiyasahu/Donut#19]
I have installed the on-site-notifications plugin from http://www.q2apro.com/plugins/on-site-notifications and it works perfectly for the Snow theme and FlatSnow theme and others themes as weel. However, if I use Donut theme (which is the one that I want to use since it is free nice and responsive), the notification icon does not appear anywhere (on the other themes it appears on the top close to username when logged in).

The problem seems to be with the Donuts theme, any help is welcome.

Q2A version: 1.7

**Comment by amiyasahu** [comment]
added for the large screen devices . As it is not responsive I am not enabling this on small screen devices
