### ISSUE TITLE
Error qa-donut-layer.php

### ISSUE THREAD

**Issue by yerbol89** [amiyasahu/Donut#22]
I use q2a dev version. https://github.com/q2a/question2answer/tree/dev

[Fri Aug 14 11:31:53 2015] [error] [client 90.143.49.17] PHP Parse error:  syntax error, unexpected '@' in /var/www/szh/data/www/szh.kz/test/qa-theme/Donut-dev/qa-donut-layer.php on line 1277, referer: http://szh.kz/test/admin/general

**Comment by amiyasahu** [comment]
will look into it . 

Which PHP version you are using ?

**Comment by amiyasahu** [comment]
It should work now . Can you please check and let me know

**Comment by yerbol89** [comment]
@amiyasahu i edit this code. After i see error log.
[Fri Aug 14 17:27:51 2015] [error] [client 2.132.176.131] PHP Parse error:  syntax error, unexpected '=', expecting ')' in /var/www/szh/data/www/szh.kz/test/qa-theme/Donut-dev/templates/top-header.php on line 6

After i edit top-header.php
```
<?php $header_left_text = donut_opt( 'top_bar_left_text'); ?>
<?php if (!empty( $header_left_text )): ?>
<?php echo $header_left_text ?>
<?php endif ?>
```
and

```
<?php $header_right_text = donut_opt( 'top_bar_right_text' ); ?>
<?php if ( !empty( $header_right_text ) ): ?>
<?php echo $header_right_text ?>
<?php endif ?>
```

Now its nice work. I use PHP Version 5.3.3-7+squeeze26

**Comment by amiyasahu** [comment]
can you paste here what did you edited . I am using PHP 5.6 , thats why I am not seeing these errors .

**Comment by yerbol89** [comment]
You code:
```
<?php if ( !empty( $header_left_text = donut_opt( 'top_bar_left_text' ) ) ): ?>
<?php echo $header_left_text ?>
<?php endif ?>
```

```
<?php if ( !empty( $header_right_text = donut_opt( 'top_bar_right_text' ) ) ): ?>
<?php echo $header_right_text ?>
<?php endif ?>
```

My code:

After i edit top-header.php
```
<?php $header_left_text = donut_opt( 'top_bar_left_text'); ?>
<?php if (!empty( $header_left_text )): ?>
<?php echo $header_left_text ?>
<?php endif ?>
```
and
```
<?php $header_right_text = donut_opt( 'top_bar_right_text' ); ?>
<?php if ( !empty( $header_right_text ) ): ?>
<?php echo $header_right_text ?>
<?php endif ?>
```

**Comment by amiyasahu** [comment]
ok , This clearly this is due to the PHP version . I will update soon .
