### ISSUE TITLE
CSS edit

### ISSUE THREAD

**Issue by yerbol89** [amiyasahu/Donut#23]
@amiyasahu its nice theme for q2a. You work nice job. Thanks.
I have any question for Donut theme.
1. Search area not 100% width.
![1](https://cloud.githubusercontent.com/assets/993795/9273783/9d0237e4-42b1-11e5-9bae-7af3299a2d1b.png)
2. Home page for mobile sidebar not 100% width.
![2](https://cloud.githubusercontent.com/assets/993795/9273794/b865e2b0-42b1-11e5-9d7d-94a59c543184.png)
3. Plase dont show text in edit bottons. Show icon and a text see after mouse tooltip.
![3](https://cloud.githubusercontent.com/assets/993795/9273843/2fc3707a-42b2-11e5-9620-c09628909095.png)
Example
![4](https://cloud.githubusercontent.com/assets/993795/9273950/fbef6dca-42b2-11e5-9d9a-fa4570f1a206.png)

**Comment by amiyasahu** [comment]
@yerbol89 , thanks for the bug reports . I am still working on these improvements .

1. This is already done . Yet to commit the code . 

Others I will be working on them .

**Comment by amiyasahu** [comment]
these issues has been fixed . Keeping only icon buttons I will push the next release
