### ISSUE TITLE
Less compiler

### ISSUE THREAD

**Issue by arioch1984** [amiyasahu/Donut#30]
Hi!
For first thank's for your great work!
This theme is awesome!

My only problem is: I'm trying to apply some changes to css and, if possible, if prefere to work on less files but I could not find any grunt or gulp file for compile them into css.

Please may you commit your less compiler to dev channel or may you help me with this question?

Thank's a lot.

**Comment by amiyasahu** [comment]
I am using http://koala-app.com/ . You can install it and just drag the less folder and drop it onto the koala app . 
Then you can start editing the less files , the app will automatically detect the changes and start compiling the less files to css .
