### ISSUE TITLE
Fb login button doesn't show up on dropdown-menu and h2 has border bottom

### ISSUE THREAD

**Issue by sep1** [amiyasahu/Donut#35]
1) http://oi60.tinypic.com/2w4jhgj.jpg

2) double border bottom for div class="qa-a-form" id="anew" http://oi61.tinypic.com/2q3c203.jpg

**Comment by amiyasahu** [comment]
The facebook login works well with the open login plugin . You can get the open login plugin here .
https://github.com/alixandru/q2a-open-login

I will check on the issue and try to make compatible with the official facebook login plugin .

**Comment by sep1** [comment]
q2a open login doesn't work well, it's obsolete and i get some errors.
Thanks ami.

**Comment by amiyasahu** [comment]
double border bottom issue is fixed here - 25bb74fd00320d47e062325e08e8f9a9f2e37e93
