### ISSUE TITLE
back to top button bug

### ISSUE THREAD

**Issue by sep1** [amiyasahu/Donut#36]
1) back to top button bug http://oi61.tinypic.com/2hx1rte.jpg
2) still having double bottom border http://oi61.tinypic.com/2q3c203.jpg

**Comment by amiyasahu** [comment]
please give Ctrl + R on your browser . it is due to browser cache

**Comment by amiyasahu** [comment]
Dont link tinypic links here . you can directly drag and drop images into the text area .

**Comment by sep1** [comment]
I'm sure it's not due to browser cache...

**Comment by amiyasahu** [comment]
Remove the theme and install freshly . This issue is not there , you can see it in the demo page
