### ISSUE TITLE
Theme broken

### ISSUE THREAD

**Issue by BatmanLives** [amiyasahu/Donut#37]
I just installed your theme, and it seems broken:
http://systemengineer.com/

Would you mind taking a look to see what might have gone wrong? Thanks!

Kenny

**Comment by yerbol89** [comment]
@BatmanLives i see you site in css link not good.
Please open 
https://github.com/amiyasahu/Donut/blob/f823c2e84d86cbaaaaca886a58770d65aaa040e9/qa-theme/Donut-theme/qa-donut-layer.php
file and delete in 61 line 'donut'     => 'css/donut.cssS? this S symbol and save file.

'donut'     => 'css/donut.css?

@amiyasahu please edit this file.

**Comment by amiyasahu** [comment]
This has been fixed. This is due to a typo in my last commit .

**Comment by BatmanLives** [comment]
Wonderful thank you!

**Comment by amiyasahu** [comment]
Cheers :smile:

**Comment by BatmanLives** [comment]
By the way, are you available for custom coding work? My email is
sanbat@gmail.com. Thanks!

Kenny
