### ISSUE TITLE
Whow i use max container width 1000px or 980px

### ISSUE THREAD

**Issue by yerbol89** [amiyasahu/Donut#38]
Example: Github use max container 980px.

How i use for Donut theme use 980px

**Comment by amiyasahu** [comment]
You need to do it from the less files - 
https://github.com/amiyasahu/Donut/blob/master/qa-theme/Donut-theme/less/bootstrap/variables.less#L285
and 
https://github.com/amiyasahu/Donut/blob/master/qa-theme/Donut-theme/less/variables.less

And after you change then you need to recompile both bootstrap and donut less files to get the css file . Make sure you do enough testing before you go to live .
