### ISSUE TITLE
Tag and blog display overlapping

### ISSUE THREAD

**Issue by arjunsuresh** [amiyasahu/Donut#39]
![blog](https://cloud.githubusercontent.com/assets/4791823/11068751/2c1174a2-87d3-11e5-9b3d-62330e0cfbf8.png)
![screenshot from 2015-11-10 16 30 17](https://cloud.githubusercontent.com/assets/4791823/11068755/304540da-87d3-11e5-9801-613f1fc6ce94.png)

**Comment by amiyasahu** [comment]
Thanks , I will take a look on this issue

**Comment by arjunsuresh** [comment]
Thanks. I have installed the newer version of Donut and every user is pretty happy with the new look. Thanks for the wonderful theme :)

And the blog display seems proper on the main site. 
http://gateoverflow.in/blogs?sort=featured

Also, I changed the background of entry-content from white as question/answer text becomes more clear with a light background. If you like it, you can add this to future versions. 
http://gateoverflow.in/26144/from-many-numbers-formed-such-that-even-digits-are-odd-places

**Comment by amiyasahu** [comment]
Thats nice , I will check

**Comment by amiyasahu** [comment]
This can be fixed with this. I will update the theme in next version 
```css
.qa-tags-rank-tag-item, .qa-q-item-tag-item, .qa-q-view-tag-item {
    padding: 5px 0;
}
```

**Comment by arjunsuresh** [comment]
Thank you :+1:

**Comment by amiyasahu** [comment]
Fixed
