### ISSUE TITLE
Banner section Ask button not visible in mobile devices. 

### ISSUE THREAD

**Issue by VGNtl** [amiyasahu/Donut#43]
![2016-01-21 20_44_28-answercloud](https://cloud.githubusercontent.com/assets/10906875/12484204/37618b96-c07f-11e5-8b5d-185de03e005f.jpg)

**Comment by amiyasahu** [comment]
This is quite expected ebhaviour . 

The user can Hit the -> button on the mobile device once he filled the question . 

If you want this in small devices then you have to change it here - 
https://github.com/amiyasahu/Donut/blob/master/qa-theme/Donut-theme/templates/site-header.php#L59

From 
```html
 <button type="submit" class="btn btn-primary btn-lg ask-btn hidden-xs">Ask !</button>
```

To 
```html
 <button type="submit" class="btn btn-primary btn-lg ask-btn">Ask !</button>
```

You need to make necessary CSS changes to make it look good on mobile devices .
