### ISSUE TITLE
Add function code for core theme?

### ISSUE THREAD

**Issue by yerbol89** [amiyasahu/Donut#45]
How i add php code for theme?

In SnowFlat theme i use qa-theme.php code add:
`public function _remove_nofollow( $str )
		{ 
			$search1 = '#<a rel="nofollow" href="http://surak.szh.kz("|/[^"]*")#i'; 
			$search2 = '#<a href="http://surak.szh.kz("|/[^"]*") rel="nofollow"#i'; 
			$replace = '<a href="http://surak.szh.kz\1'; 
			$str = preg_replace( $search1, $replace, $str ); 
			$str = preg_replace( $search2, $replace, $str ); 
			return $str; 
		}

		public function q_view_content($q_view) 
		{ 
			if ( !empty($q_view['content']) ) 
				$q_view['content'] = $this->_remove_nofollow( $q_view['content'] ); 
			parent::q_view_content($q_view); 
		} 
		public function a_item_content($a_item) 
		{ 
			if ( !empty($a_item['content']) ) 
				$a_item['content'] = $this->_remove_nofollow( $a_item['content'] ); 
			parent::a_item_content($a_item); 
		} 
		public function c_item_content($c_item) 
		{ 
			if ( !empty($c_item['content']) ) 
				$c_item['content'] = $this->_remove_nofollow( $c_item['content'] ); 
			parent::c_item_content($c_item); 
		}
		
		private $suffixes = array('', 'k', 'm');
 
		private function formatViews($size, $precision = 1) {
			$base = log($size) / log(1000);
			return round(pow(1000, $base - floor($base))) . $this->suffixes[floor($base)];
		}
		 
		private function updateViewCount(&$questionItem) {
			if (isset($questionItem['views_raw'], $questionItem['views']['data'])) {
				$questionItem['views']['data'] = $this->formatViews($questionItem['views_raw']);
			}
		}
		 
		public function q_list_item($q_item) {
			$this->updateViewCount($q_item);
			qa_html_theme_base::q_list_item($q_item);
		}
		
		public function main_parts($content) {
		  $newcontent = array();
		  if(isset($content['a_form']) && isset($content['a_list'])) {
			$a_form = $content['a_form'];
			$a_list = $content['a_list'];
			foreach($content as $key => $item) {
			  if($key == 'a_form')
				$newcontent['a_list'] = $a_list;
			  else if($key == 'a_list')
				$newcontent['a_form'] = $a_form;
			  else
				$newcontent[$key] = $item;
			}
			qa_html_theme_base::main_parts($newcontent);
		  } else
			qa_html_theme_base::main_parts($content);
		}`

**Comment by amiyasahu** [comment]
from which theme / plugin this code comes from ?

**Comment by amiyasahu** [comment]
this should be a simple plugin . closing this for now
