### ISSUE TITLE
 full width "footer" at small displays

### ISSUE THREAD

**Issue by Soeldner** [amiyasahu/Donut#47]
changes in qa-donut-layer.php

Line 406
```
$this->output( '<div class="qa-sidepanel col-md-3 pull-right">' );
```
into
```
$this->output( '<div class="qa-sidepanel col-md-3 col-xs-12 pull-right">' );
```

![q2a_donut_theme_footer_xs_display_ba](https://cloud.githubusercontent.com/assets/1868211/13159012/fcb2e68a-d68f-11e5-8ef5-55e44806a5e4.jpg)

**Comment by amiyasahu** [comment]
Which browser you are using. 
making it col-md-3 , it automatically makes full width for xs

**Comment by Soeldner** [comment]
OS: Mint
Firefox 44.0.2
Opera 12.16

I cant recreate that in a standard bootstrap template :(

**Comment by Soeldner** [comment]
another screenshot HTC one

![screenshot_2016-02-19-08-43-57](https://cloud.githubusercontent.com/assets/1868211/13169397/6b1e95e2-d6e5-11e5-8ee5-42aa76920e9a.png)

**Comment by amiyasahu** [comment]
Ok , I will test and merge your PR . Thank you
