### ISSUE TITLE
Post Action Buttons Not Working

### ISSUE THREAD

**Issue by idevwebs** [amiyasahu/Donut#54]
None of the buttons on the More Actions menu are working. For example, if I click Hide the form is posted and the page loads, but nothing happens. I've confirmed these actions work using the default theme. So this is donut theme specific. Those are pretty critical items.

What can I do to fix this? I can't Hide or Close questions. Please advise.

Thank you

**Comment by amiyasahu** [comment]
This works fine, I have tested it and demo also works good. 

Can you tell me how to reproduce this error.

**Comment by sunnogo** [comment]
I have the same issue. When I click the `More Action` button to edit the question, nothing happened.

* Q2A, v1.7.5
* Donut, v1.6.3.1
* Chrome, v61.0.3163.100 (64bit)
* Windows 7

Pls tell me what other informations I need to collect.

**Comment by sunnogo** [comment]
Sorry, I have found out what's wrong.

I use lighttpd, but deny access the following directory. After delete this configuration, it works fine.

```
$HTTP["url"] =~ "^/(qa-content|qa-external-example|qa-include|qa-lang|qa-plugin|qa-tests|qa-themes)" {
  url.access-deny = ( "" )
}
```
