### ISSUE TITLE
How i add <li> class

### ISSUE THREAD

**Issue by yerbol89** [amiyasahu/Donut#57]
![456](https://cloud.githubusercontent.com/assets/993795/15705746/62b75bf4-2812-11e6-8cfa-14f95d0dfac9.png)
![otbasyi-ba--yityi](https://cloud.githubusercontent.com/assets/993795/15705747/62d9147e-2812-11e6-9b24-f8f12543156d.jpg)

**Comment by amiyasahu** [comment]
You can add it like this here  - 
https://github.com/amiyasahu/Donut/blob/master/qa-theme/Donut-theme/qa-donut-layer.php#L500

```php
$this->content[ 'navigation' ][ 'main' ][ 'donut-theme' ] = array(
    'url'      => 'https://github.com/amiyasahu/Donut',
    'label'    => 'Donut theme',
    'selected' => 0,
);
```

**Comment by yerbol89** [comment]
@amiyasahu bro help me.
How i add li class?
Please tell me class css add php code.

![1](https://cloud.githubusercontent.com/assets/993795/19836269/02107266-9ec5-11e6-88be-0ad4b1ed659d.png)

**Comment by amiyasahu** [comment]
Just use the PHP code I have given in my previous comment.

**Comment by yerbol89** [comment]
@amiyasahu Its true?

```
function body_header() // adds login bar, user navigation and search at top of page in place of custom header content
        {
            if ( !empty( $this->content['navigation']['main'] ) ) {
                $this->output( $this->donut_nav_bar( $this->content['navigation'] ) );
                unset( $this->content['navigation']['main'] );
            }
			$this->content[ 'navigation' ][ 'main' ][ 'donut-theme' ] = array(
				'url'      => 'https://github.com/amiyasahu/Donut',
				'label'    => 'Donut theme',
				'selected' => 0,
			);
        }
```

**Comment by amiyasahu** [comment]
No @yerbol89 , use it like below - 

```php
function body_header() // adds login bar, user navigation and search at top of page in place of custom header content
{
    if ( !empty( $this->content['navigation']['main'] ) ) {
        $this->content[ 'navigation' ][ 'main' ][ 'donut-theme' ] = array(
            'url'      => 'https://github.com/amiyasahu/Donut',
            'label'    => 'Donut theme',
            'selected' => 0,
        );

        $this->output( $this->donut_nav_bar( $this->content['navigation'] ) );
        unset( $this->content['navigation']['main'] );
    }
}
``

**Comment by yerbol89** [comment]
@amiyasahu thanks its work.
After i'm 0 to 1 add class active. :) 
I add after selected **'selected' => 1,** class 'classs' => 'radio' work fine.

And i want one question?
How i open link new target blank page?
I add
'target' => '_blank'
but its not work.

```
function body_header() // adds login bar, user navigation and search at top of page in place of custom header content
{
    if ( !empty( $this->content['navigation']['main'] ) ) {
        $this->content[ 'navigation' ][ 'main' ][ 'donut-theme' ] = array(
            'url'      => 'https://github.com/amiyasahu/Donut',
            'label'    => 'Donut theme',
            'selected' => 1,
            'classs' => 'radio',
        );

        $this->output( $this->donut_nav_bar( $this->content['navigation'] ) );
        unset( $this->content['navigation']['main'] );
    }
} 
```

**Comment by amiyasahu** [comment]
Instead of changing the code, you should use `Admin -> Pages -> Add Link` option from admin panel. This will be less hassle. Sorry I misguided you to change the code.

**Comment by yerbol89** [comment]
@amiyasahu i use Admin -> Pages -> Add Link option from admin panel. But first Donut theme delete class in li and open target blank not work. I enable open link new window but target blank dont work.

**Comment by amiyasahu** [comment]
I will check and fix in next version.
