### ISSUE TITLE
Left side menu botton views botton scroll?

### ISSUE THREAD

**Issue by yerbol89** [amiyasahu/Donut#62]
![1](https://cloud.githubusercontent.com/assets/993795/19439841/73d16096-94a1-11e6-8b0d-14bc353dad13.png)

![2](https://cloud.githubusercontent.com/assets/993795/19439847/78d39c62-94a1-11e6-87cd-9f490601fe7a.png)

**Comment by amiyasahu** [comment]
This is an expected behaviour.
