### ISSUE TITLE
.qa-form-tall-note style is missing

### ISSUE THREAD

**Issue by pupi1985** [amiyasahu/Donut#65]
I've seen the wide note style being properly applied but not the tall one. Same style looks good.

**Comment by amiyasahu** [comment]
Did you mean - wide note style is applied but not the tall one?

**Comment by pupi1985** [comment]
Right, typo fixed.

**Comment by amiyasahu** [comment]
Please check the dev branch. And let me know if you still have this issue in any page.

**Comment by pupi1985** [comment]
Thanks. It seems to be fixed now.
