### ISSUE TITLE
Issues while adding new sections to profile

### ISSUE THREAD

**Issue by pupi1985** [amiyasahu/Donut#66]
New sections in profile need custom HTML as the CSS selector is too specific. This leads to issues such as this one:

![screenshot](https://cloud.githubusercontent.com/assets/1449790/19840067/dde3d858-9ecc-11e6-8bc2-1bdd56a89aec.png)

That can be fixed per plugin but it makes sense for the theme to be ready to this section being extended. Check the selector in SnowFlat and you'll see what I mean. BTW, positioning looks perfectly fine.

**Comment by amiyasahu** [comment]
Please check this in dev branch and let me know if you are facing any issue.

**Comment by pupi1985** [comment]
Great. Now new profile sections don't require custom CSS for Donut :) It looks great. Thanks.
