### ISSUE TITLE
Bookstrap URL https issue 

### ISSUE THREAD

**Issue by arjunsuresh** [amiyasahu/Donut#70]
From couple of days Donut theme is coming messy in Chromium browser due to bootstrap css not being downloaded. This is sue to a "https" issue. Fixed by the following in utils/donut-options.php

--const BS_CSS_CDN = 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css';
++const BS_CSS_CDN = '//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css';

**Comment by amiyasahu** [comment]
will fix it @arjunsuresh . Thanks for bringing in notice
