### ISSUE TITLE
View count size is more?

### ISSUE THREAD

**Issue by arjunsuresh** [amiyasahu/Donut#72]
![screenshot from 2017-01-29 14-23-28](https://cloud.githubusercontent.com/assets/4791823/22407152/ddd43282-e62e-11e6-8ffb-80ea1f0a3660.png)

As seen in the above pic, the view count in blog pages is slightly on the higher side. Can this be fixed?

**Comment by amiyasahu** [comment]
This has been fixed in recent version of theme and plugin. Now the page looks better. Closing this issue, please re-open if you still have the issue.
