### ISSUE TITLE
no tags

### ISSUE THREAD

**Issue by gibbywilson** [amiyasahu/Donut#74]
when there are no tags and you click the tag menu you see an error on the page

`Notice: Undefined index: ranking_tags in /£££££££££££££££/qa-theme/Donut-theme/qa-donut-layer.php on line 1115`

**Comment by amiyasahu** [comment]
can you please specify which version you have installed?

**Comment by gibbywilson** [comment]
1.6.3.1

thanks

**Comment by atozsoft** [comment]
hi,

i have same issue. thanks

**Comment by amiyasahu** [comment]
It will be fixed in next version
