### ISSUE TITLE
SMTP not working

### ISSUE THREAD

**Issue by pintraj** [amiyasahu/Donut#76]
Hi
I have installed you Donut theme and I have configured the SMTP server but I am unable to send the email to the registered user. It says some error occurred. Please let me know how to configure the SMTP

Note: I have installed in VPS(Digital Ocean)

**Comment by baoc75** [comment]
Check your SMTP server configurations, as well as your DNS, TXT, MX records for your email hosting. 
P.s: Please remind that Donut is a theme for Q2A.

**Comment by amiyasahu** [comment]
This has nothing to do with Donut. It is just a theme. As @baoc75 suggested, please check your SMTP settings.
