### ISSUE TITLE
Some vital buttons not shown for open-login plugin

### ISSUE THREAD

**Issue by poVoq** [amiyasahu/Donut#77]
When I enable the Donut theme most of the open-login plugin works fine, but when I try to merge two accounts, it only shows the drop-down of which account to keep but but no option to confirm. Without the Donut theme a "contine" button appears that is used to confirm the action.
Any simple fix for this?

**Comment by amiyasahu** [comment]
Can you please put the screenshot for this issue?

**Comment by poVoq** [comment]
I have since completely changed my Q2Aset-up, but it seems someone else found the reason here:
https://github.com/alixandru/q2a-open-login/issues/78

**Comment by amiyasahu** [comment]
Are you still getting this error?

**Comment by poVoq** [comment]
Yes, but on another theme, SnowLight. But the fix is mentioned in the above link.
