### ISSUE TITLE
Donut call an query to users table while SSO is enabled

### ISSUE THREAD

**Issue by baoc75** [amiyasahu/Donut#78]
I have just have done intergrating SSO with my Q2A site. However, I don't know why Donut theme still call to users table, while SSO already enabled.
PHP error logs:
"PHP Question2Answer MySQL query error 1146: Table '_users' doesn't exist - Query: SELECT ask_users.userid, passsalt, HEX(passcheck) AS passcheck, passhash, email, level, emailcode, handle, UNIX_TIMESTAMP(created) AS created, sessioncode, sessionsource, flags, UNIX_TIMESTAMP(loggedin) AS loggedin, loginip, UNIX_TIMESTAMP(written) AS written, writeip, BINARY avatarblobid AS avatarblobid, avatarwidth, avatarheight, points, wallposts FROM ask_users LEFT JOIN ask_userpoints ON ask_userpoints.userid=ask_users.userid WHERE ask_users.userid='1'"
If I switch to another theme, Q2A works fine.

**Comment by baoc75** [comment]
Because SSO was enabled after Q2A generated its database, therefore the foreign keys will match the qa_users table. Just remove those foreign keys and it would work fine.

**Comment by trulyfurqan** [comment]
Hi,
I've somehow managed to fix this issue.

Kindly check my answer to this issue here: [https://github.com/amiyasahu/Donut/issues/73#issuecomment-433012863](https://github.com/amiyasahu/Donut/issues/73#issuecomment-433012863)
