### ISSUE TITLE
How to remove powered by in fotter

### ISSUE THREAD

**Issue by rajakoppula** [amiyasahu/Donut#79]
Hi, after i changed to donut, i see that my website got attracted with a lot of spam bots, may be because it ads powered by in footer, then i want to remove or modify it to hide foot prints for spam bots, so you please tell me how to do that.

Best regards,
Raja.

**Comment by arjunsuresh** [comment]
How's "Powered by" linked to spam?

**Comment by rajakoppula** [comment]
Their use strings like site:.com "powered by cmsname" in search engine to find such websites for to create spam profiles.

**Comment by rajakoppula** [comment]
i got like 200 spam registrations in only 2 days, and i also observed their using such string to find the sites from search engines.

**Comment by arjunsuresh** [comment]
Never knew this. But anyway after enabling Google recapcha spam accounts have been practically nill.

**Comment by amiyasahu** [comment]
Better try Google recaptcha. 

Here is the giude to remove powered by - http://www.question2answer.org/qa/6602/how-do-you-remove-the-powered-by
