### ISSUE TITLE
I have installed Donut Theme on my new installed question 2 answer

### ISSUE THREAD

**Issue by link2admission** [amiyasahu/Donut#81]
Hello Sir/Ma,

I have stalled Donut theme on my q2a website and i followed the requested procedure. So after the installation and setup, i open my q2a website and i discover that the theme did not take any effect on my site.

I uninstall it and install it again following the right procedure and still not working..

Please how can i fix this error?

Thanks

**Comment by brijeshjain13** [comment]
Verify the version of the Question2Answer platform and the placement of directories.

**Comment by amiyasahu** [comment]
What is the error you are getting in the error log?
