### ISSUE TITLE
How do I update "FontAwasome" to version 5?

### ISSUE THREAD

**Issue by mcdasdmr** [amiyasahu/Donut#83]
Hi,

Your theme is amazing. Thank you so much. But I have a question.

How do I update "FontAwasome" to version 5?

**Comment by amiyasahu** [comment]
You need to update the font awesome under qa-theme/Donut-theme/css and  qa-theme/Donut-theme/fonts. 

If you are using CDN, then update the cdn link here --> https://github.com/amiyasahu/Donut/blob/master/qa-theme/Donut-theme/utils/donut-options.php#L19
