### ISSUE TITLE
Avatar of logged in user not shown

### ISSUE THREAD

**Issue by premjeras** [amiyasahu/Donut#84]
The theme is always loading the default avatar for the logged in user (Q2A v. 1.80)

**Comment by Schoaf** [comment]
same here. Avatar shows up on posts but not in the top right corner for the menu button of the logged-in-user.
It seems they changed something in the avatar handling. Not sure if it's causing this issue though.
https://github.com/q2a/question2answer/pull/468

**Comment by premjeras** [comment]
I found the solution, posted [here](http://www.question2answer.org/qa/62655/avatar-of-logged-in-user-on-donut-theme-not-shown).

**Comment by Schoaf** [comment]
I can happily confirm that the fix works. :)
Thanks.

**Comment by amiyasahu** [comment]
I will check on this and make a permanent fix.
