### ISSUE TITLE
front page error

### ISSUE THREAD

**Issue by aonesilent** [amiyasahu/Donut#91]
![default](https://user-images.githubusercontent.com/19368999/45603521-36de5500-ba5f-11e8-9daf-bc0ccb701a4d.png)

php 7.2.4
Donut 2.0

**Comment by dainar** [comment]
go to qa-theme/Donut-theme/qa-donut-layer.php

and edit line from

if (count($sub_navigation )) {
to
 if ( !empty( $sub_navigation ) ) {
