### ISSUE TITLE
Schema.org error

### ISSUE THREAD

**Issue by tryazi** [amiyasahu/Donut#98]
Hi Ami
I want to use the theme but it causes structural data errors. Some arrangements are needed for Schema.org.
I am not receiving a data error in the Snowflat theme. Version 1.8.1 bugfix tree

The latest version of your theme. Can you help with that?

**Comment by amiyasahu** [comment]
@tryazi , thank you for reporting the error. @svivian has fixed the issue with #99 . I will make a new release for this change. 
I am closing this as the change present in the master branch. 
If you are still facing the issue, you can reopen.

**Comment by taufik7000** [comment]
"mainEntity.name" is still missing .. i gote some error on my site..

**Comment by amiyasahu** [comment]
Can you put the screenshot of this issue?

**Comment by taufik7000** [comment]
https://prnt.sc/lrs5k3
https://prnt.sc/lrs5nl

**Comment by amiyasahu** [comment]
This error is coming for which page?

**Comment by taufik7000** [comment]
question page sir ...

**Comment by taufik7000** [comment]
error on <div class="qa-main col-md-9 col-xs-12 pull-left" itemprop="mainEntity" itemscope itemtype="http://schema.org/Question">

the column mainEntity.name is missing
